djangobasico/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('favoritos.urls'))
    
]

favoritos/urls.py
from django.urls import path


from .views import *

app_name = 'favoritos'

urlpatterns = [
    path('', index_favoritos, name='index'), #127.0.0.1:8000
    path('crear', crear_favoritos, name='crear'),
    path('borrar/<int:pk>', borrar_favoritos, name='borrar'),
    path('detalle/<int:pk>', detalle_favoritos, name='detalle'),
    path('actualizar/<int:pk>', actualizar_favoritos, name='actualizar'),
]

favoritos/models.py
from django.db import models

# Create your models here.

class Favoritos(models.Model):
    nombre = models.CharField(max_length=50, blank=True)
    url = models.URLField()

favoritos/forms.py
from django import forms
from .models import Favoritos


class FavoritoForm(forms.Form):
    nombre = forms.CharField()
    url = forms.URLField()



class FavoritoModelForm(forms.ModelForm):
    class Meta:
        model = Favoritos
        fields = '__all__' #['nombre']

favoritos/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from .models import Favoritos
from .forms import FavoritoModelForm

# Create your views here.

def index_favoritos(request):
    favoritos_lista = Favoritos.objects.all()

    context = {
        'favoritos_lista':favoritos_lista
    }

    return render(request, 'favoritos/lista.html', context)


def crear_favoritos(request):

    form = FavoritoModelForm()

    if request.method == 'POST':
        form = FavoritoModelForm(request.POST)
        if form.is_valid():
           form.save()
        else:
            print(form.errors)
        

    context = {
        'form':form,
        'titulo': 'Crear favorito'
    }

    return render(request, 'favoritos/crear.html', context)


def borrar_favoritos(request, pk):
    Favoritos.objects.get(pk=pk).delete()
    return redirect('favoritos:index')
    # return redirect(reverse('favoritos:borrar', kwargs={'pk':pk}))


def detalle_favoritos(request, pk):
    favorito = Favoritos.objects.get(pk=pk)
    return render(request, 'favoritos/detalle.html', context={'object':favorito})


def actualizar_favoritos(request, pk):
    favorito = Favoritos.objects.get(pk=pk)

    form = FavoritoModelForm(instance=favorito)

    if request.method == 'POST':
        form = FavoritoModelForm(request.POST, instance=favorito)

        if form.is_valid():
           form.save()
        else:
            print(form.errors)
        

    context = {
        'form':form,
        'titulo': 'Actualizar favorito'
    }

    return render(request, 'favoritos/crear.html', context)

favoritos/templates/favoritos/crear.html
{% extends 'base_bs5.html' %}

{% block main %}

    <div class="container">

        <h1>{{ titulo }}</h1>
        <p>
            <a href=" {% url 'favoritos:index' %}" class="btn btn-outline-primary">Atras</a>
        </p>
    
        <form method='post' class="form-control">
            {% csrf_token %}
    
            {{ form.as_p }}
    
    
            {% comment %} {% comment %} <label>Nombre</label>
            <input type='text' name='nombre'></input>
    
            <label>url</label>
            <input type='text' name='url'></input> {% endcomment %}
    
            <input type='submit' class="btn btn-outline-primary"></input> 
        </form>
    </div>


{% endblock main %}

favoritos/templates/favoritos/detalle.html
{% extends 'base_bs5.html' %}

{% block main %}

    <div class="container">

        <h1>Detalle Favorito</h1>
        <p><a href=" {% url 'favoritos:index' %}" class="btn btn-outline-primary">Atras</a></p>
        <p>Nombre: {{ object.nombre }}</p>
        <p>URL: {{ object.url }}</p>
        {% comment %} ESTA FORMA PARA QUE ME LO MUESTRE COMO ENLACE {% endcomment %}
        <p>URL: <a href=" {{ object.url }}"> {{ object.url }}</a></p>
    </div>


{% endblock main %}

favoritos/templates/favoritos/lista.html
{% extends 'base_bs5.html' %}

{% block main %}

    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Lista Favoritos</h1>
                <p>
                    <a href="{% url 'favoritos:crear' %}" class="btn btn-outline-primary">Nuevo</a>
                </p>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>URL</th>
                            <th></th>
                        </tr>
                    </thead>
            
                    <tbody>
                        {% for favorito in favoritos_lista %}
                        <tr>
                            <td>{{ favorito.nombre }}</td>
                            <td>{{ favorito.url }}</td>
                            <td>
                                <a href="{% url 'favoritos:borrar' favorito.pk %}" class="btn btn-outline-danger m-2">Borrar</a>
                                <br>
                                <a href="{% url 'favoritos:detalle' favorito.pk %}" class="btn btn-outline-info m-2">Detalle</a>
                                <br>
                                <a href="{% url 'favoritos:actualizar' favorito.pk %}" class="btn btn-outline-primary m-2">Actualizar</a>
            
                            </td>
            
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
{% endblock main %}

templates/base_bs5.html
<!doctype html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Favoritos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>

  <body>

    {% block main %}
    
    {% endblock  %}
   
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>

</html>

templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
</head>

<body>
    
    <h1>Favoritos</h1>

</body>

</html>